services:
  postgres-db:
    container_name: ietpostgresdb
    image: postgres
    environment:
      POSTGRES_DB: gombahaz
      POSTGRES_USER: admin
      PGUSER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER 
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5432:5432"
    networks: 
      - db-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgres-admin:
    container_name: ietpostgresadmin
    image: dpage/pgadmin4
    ports: 
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks: 
      - db-network
    volumes:
      - pg-admin-data:/var/lib/pgadmin
  backend:
    container_name: ietbackenddotnet
    image: ${DOCKER_REGISTRY-}gombahaz
    build:
      context: ./Gombahaz
      dockerfile: Gombahaz/Dockerfile
    networks:
      - db-network
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
  frontend-angular:
   container_name: ietfrontendangular
   build: ./Frontend/
   image: frontend-angular:v1
   ports:
     - "8082:8090"
   networks:
     - db-network
   depends_on:
     - backend

volumes:
    pg-admin-data:
    postgres-data:

networks:
  db-network:
    driver: bridge
