// <auto-generated />
using System;
using Gombahaz.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gombahaz.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240427112219_datasetitemtest")]
    partial class datasetitemtest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gombahaz.Models.DataSetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("COLevel")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DataObserved")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<double?>("SoilMoisture")
                        .HasColumnType("double precision");

                    b.Property<double?>("SoilTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("DataSet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            COLevel = 0.25,
                            DataObserved = new DateTime(2024, 4, 27, 8, 22, 11, 0, DateTimeKind.Utc),
                            Humidity = 95.0,
                            ResourceId = 1,
                            SoilMoisture = 30.0,
                            SoilTemperature = 15.0,
                            Temperature = 15.0
                        });
                });

            modelBuilder.Entity("Gombahaz.Models.ResourceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Resource");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1111 Budapest József Attila utca 151.",
                            Comment = "Minden műszer megfelelően működik.",
                            Description = "Csiperkegomba termesztésre használják.",
                            Name = "Csiperke1 termesztőház",
                            Size = "150x30x10m"
                        },
                        new
                        {
                            Id = 2,
                            Address = "2222 Debrecen Kossuth utca 20.",
                            Comment = "Ideális környezet a gombák fejlődéséhez.",
                            Description = "Különböző gombafajták termesztésére alkalmas.",
                            Name = "GombaFalu gazdaság",
                            Size = "120x25x8m"
                        },
                        new
                        {
                            Id = 3,
                            Address = "3333 Szeged Ady Endre út 5.",
                            Comment = "A legfrissebb technológiákat alkalmazzák a termesztés során.",
                            Description = "Kizárólag biogombák termesztésére specializálódott.",
                            Name = "Zöld Kapu GombaFarm",
                            Size = "100x20x6m"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4444 Pécs Széchenyi tér 10.",
                            Comment = "A legmagasabb minőséget garantálják.",
                            Description = "Kis- és nagykereskedelmi gombaellátást biztosít.",
                            Name = "GombaPalota Kertészete",
                            Size = "80x15x5m"
                        },
                        new
                        {
                            Id = 5,
                            Address = "5555 Győr Árpád út 3.",
                            Comment = "Modern és hatékony termesztési módszereket alkalmaznak.",
                            Description = "Többféle gombafajta termesztésére szakosodott.",
                            Name = "Gombavilág Gazdasági Komplexum",
                            Size = "130x25x7m"
                        },
                        new
                        {
                            Id = 6,
                            Address = "6666 Szombathely Bajcsy-Zsilinszky út 15.",
                            Comment = "Környezetbarát termelési folyamatokat alkalmaznak.",
                            Description = "Főként shiitake és laskagomba termesztésére fókuszálnak.",
                            Name = "GombaBirodalom Termelőház",
                            Size = "110x20x6m"
                        },
                        new
                        {
                            Id = 7,
                            Address = "7777 Nyíregyháza Szent István út 30.",
                            Comment = "Nemzetközi minősítésű termékekkel rendelkeznek.",
                            Description = "A legújabb gomba termesztési technológiákat használják.",
                            Name = "Gombasziget Gombatelep",
                            Size = "140x30x8m"
                        },
                        new
                        {
                            Id = 8,
                            Address = "8888 Miskolc Bartók Béla út 5.",
                            Comment = "A legtisztább környezetben termelik gombáikat.",
                            Description = "Kizárólag organikus gombák termesztésével foglalkoznak.",
                            Name = "Boróka GombaFarm",
                            Size = "100x18x6m"
                        },
                        new
                        {
                            Id = 9,
                            Address = "9999 Kecskemét Arany János út 2.",
                            Comment = "Az üvegház kiváló növekedési környezetet biztosít.",
                            Description = "Magas minőségű csiperkegombák termesztésére specializálódtak.",
                            Name = "GombaGazda Üvegháza",
                            Size = "90x16x5m"
                        },
                        new
                        {
                            Id = 10,
                            Address = "1010 Székesfehérvár Petőfi Sándor út 7.",
                            Comment = "A helyi piacokon nagy népszerűségnek örvendenek.",
                            Description = "Különleges ízű és formájú gombák termesztésére specializálódtak.",
                            Name = "Zöldfülű Gombatermesztő Kert",
                            Size = "120x22x7m"
                        });
                });

            modelBuilder.Entity("Gombahaz.Models.DataSetItem", b =>
                {
                    b.HasOne("Gombahaz.Models.ResourceItem", "Resource")
                        .WithMany("DataSets")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Gombahaz.Models.ResourceItem", b =>
                {
                    b.Navigation("DataSets");
                });
#pragma warning restore 612, 618
        }
    }
}
